service: dynamodb-lambda

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  deploymentMethod: direct
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.dynamodbTableName}

plugins:
  - serverless-iam-roles-per-function
  - serverless-plugin-scripts
  - serverless-s3-sync
  - serverless-prune-plugin
  # dev
  - serverless-dynamodb
  - serverless-offline

custom:
  prefix: ${self:service}-${self:provider.stage}-
  dynamodbTableName: ${self:custom.prefix}-posts-table
  frontendBucketName: ${self:custom.prefix}-frontend
  scripts:
    hooks:
      "aws:deploy:deploy:updateStack": "LAMBDA_ENDPOINT=$(yarn run serverless info --stage ${self:provider.stage} --verbose | grep 'endpoint' | rev | cut -d ' ' -f1 | rev) yarn run build:frontend"
  s3Sync:
    - bucketName: ${self:custom.frontendBucketName}
      localDir: ./.build/frontend/
      deleteRemoved: true
  prune:
    automatic: true
    number: 0

  serverless-offline:
    reloadHandler: true
    httpPort: 3001

  serverless-dynamodb:
    start:
      noStart: true

  functionEvents:
    perEnv:
      prod: ""
      stg: ""
      dev:
        - http:
            path: /{proxy+}
            method: any

resources:
  Resources:
    MainTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamodbTableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    FrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.frontendBucketName}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    FrontendBucketAccessPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: FrontendBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.frontendBucketName}/*
  Outputs:
    FrontendUrl:
      Value: "http://${self:custom.frontendBucketName}.s3-website-${self:provider.region}.amazonaws.com"

functions:
  app:
    handler: ./src/backend/entry-point-app.handler
    name: ${self:custom.prefix}-app
    memorySize: 128 # mb
    timeout: 5 # seconds
    url: true
    events: ${self:custom.functionEvents.perEnv.${self:provider.stage}}

    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
          - "dynamodb:GetItem"
          - "dynamodb:Scan"
        Resource: !GetAtt MainTable.Arn
